const data = [
  {
    "title": "Dos localizaciones únicas en Madrid y Barcelona para crear cualquier contenido audiovisual",
    "id_exponent": 2,
    "date_workshop": "20-12-2023 13:00 PM",
    "intervention": 2,
    "id_in_test": null,
    "id_output_test": null,
    "id_invitation": 2,
    "status": "En proceso",
    "number_registered": 0,
    "link": "www.sssdsd.com",
    "rrss": 100,
    "sms": 20,
    "mail": 10
  },
  {
    "title": "Dos localizaciones únicas en Madrid y Barcelona para crear cualquier contenido audiovisual",
    "id_exponent": 2,
    "date_workshop": "20-12-2023 13:00 PM",
    "intervention": 2,
    "id_in_test": 'hshshhshs',
    "id_output_test": 'jsjsjsjsj',
    "id_invitation": null,
    "status": "Finalizado",
    "number_registered": 100,
    "link": "www.sssdsd.com",
    "rrss": 100,
    "sms": 0,
    "mail": 10
  },
  {
    "title": "Dos localizaciones únicas en Madrid y Barcelona para crear cualquier contenido audiovisual",
    "id_exponent": 2,
    "date_workshop": "20-12-2023 13:00 PM",
    "intervention": 2,
    "id_in_test": null,
    "id_output_test": null,
    "id_invitation": 3,
    "status": "Cancelado",
    "number_registered": 20,
    "link": null,
    "rrss": 10,
    "sms": 20,
    "mail": 10
  },
  {
    "title": "Dos localizaciones únicas en Madrid y Barcelona para crear cualquier contenido audiovisual",
    "id_exponent": 2,
    "date_workshop": "20-12-2023 13:00 PM",
    "intervention": 2,
    "id_in_test": null,
    "id_output_test": null,
    "id_invitation": 2,
    "status": "En proceso",
    "number_registered": 0,
    "link": "www.sssdsd.com",
    "rrss": 100,
    "sms": 20,
    "mail": 10
  },
  {
    "title": "Sorprende con un espacio actual, único y fresco.",
    "id_exponent": 2,
    "date_workshop": "20-12-2023 13:00 PM",
    "intervention": 2,
    "id_in_test": 'hshshhshs',
    "id_output_test": 'jsjsjsjsj',
    "id_invitation": null,
    "status": "Finalizado",
    "number_registered": 100,
    "link": "www.sssdsd.com",
    "rrss": 100,
    "sms": 0,
    "mail": 10
  },
  {
    "title": "Sorprende con un espacio actual, único y fresco.",
    "id_exponent": 2,
    "date_workshop": "20-12-2023 13:00 PM",
    "intervention": 2,
    "id_in_test": null,
    "id_output_test": null,
    "id_invitation": 3,
    "status": "Cancelado",
    "number_registered": 20,
    "link": null,
    "rrss": 10,
    "sms": 20,
    "mail": 10
  },
  {
    "title": "Sorprende con un espacio actual, único y fresco.",
    "id_exponent": 2,
    "date_workshop": "20-12-2023 13:00 PM",
    "intervention": 2,
    "id_in_test": null,
    "id_output_test": null,
    "id_invitation": 2,
    "status": "En proceso",
    "number_registered": 0,
    "link": "www.sssdsd.com",
    "rrss": 100,
    "sms": 20,
    "mail": 10
  },
  {
    "title": "Sorprende con un espacio actual, único y fresco.",
    "id_exponent": 2,
    "date_workshop": "20-12-2023 13:00 PM",
    "intervention": 2,
    "id_in_test": 'hshshhshs',
    "id_output_test": 'jsjsjsjsj',
    "id_invitation": null,
    "status": "Finalizado",
    "number_registered": 100,
    "link": "www.sssdsd.com",
    "rrss": 100,
    "sms": 0,
    "mail": 10
  },
  {
    "title": "Sorprende con un espacio actual, único y fresco.",
    "id_exponent": 2,
    "date_workshop": "20-12-2023 13:00 PM",
    "intervention": 2,
    "id_in_test": null,
    "id_output_test": null,
    "id_invitation": 3,
    "status": "Cancelado",
    "number_registered": 20,
    "link": null,
    "rrss": 10,
    "sms": 20,
    "mail": 10
  },
  {
    "title": "Sorprende con un espacio actual, único y fresco.",
    "id_exponent": 2,
    "date_workshop": "20-12-2023 13:00 PM",
    "intervention": 2,
    "id_in_test": null,
    "id_output_test": null,
    "id_invitation": 2,
    "status": "En proceso",
    "number_registered": 0,
    "link": "www.sssdsd.com",
    "rrss": 100,
    "sms": 20,
    "mail": 10
  },
  {
    "title": "Sorprende con un espacio actual, único y fresco.",
    "id_exponent": 2,
    "date_workshop": "20-12-2023 13:00 PM",
    "intervention": 2,
    "id_in_test": 'hshshhshs',
    "id_output_test": 'jsjsjsjsj',
    "id_invitation": null,
    "status": "Finalizado",
    "number_registered": 100,
    "link": "www.sssdsd.com",
    "rrss": 100,
    "sms": 0,
    "mail": 10
  },
  {
    "title": "Sorprende con un espacio actual, único y fresco.",
    "id_exponent": 2,
    "date_workshop": "20-12-2023 13:00 PM",
    "intervention": 2,
    "id_in_test": null,
    "id_output_test": null,
    "id_invitation": 3,
    "status": "Cancelado",
    "number_registered": 20,
    "link": null,
    "rrss": 10,
    "sms": 20,
    "mail": 10
  },
  {
    "title": "Sorprende con un espacio actual, único y fresco.",
    "id_exponent": 2,
    "date_workshop": "20-12-2023 13:00 PM",
    "intervention": 2,
    "id_in_test": null,
    "id_output_test": null,
    "id_invitation": 2,
    "status": "En proceso",
    "number_registered": 0,
    "link": "www.sssdsd.com",
    "rrss": 100,
    "sms": 20,
    "mail": 10
  },
  {
    "title": "Sorprende con un espacio actual, único y fresco.",
    "id_exponent": 2,
    "date_workshop": "20-12-2023 13:00 PM",
    "intervention": 2,
    "id_in_test": 'hshshhshs',
    "id_output_test": 'jsjsjsjsj',
    "id_invitation": null,
    "status": "Finalizado",
    "number_registered": 100,
    "link": "www.sssdsd.com",
    "rrss": 100,
    "sms": 0,
    "mail": 10
  },
  {
    "title": "Sorprende con un espacio actual, único y fresco.",
    "id_exponent": 2,
    "date_workshop": "20-12-2023 13:00 PM",
    "intervention": 2,
    "id_in_test": null,
    "id_output_test": null,
    "id_invitation": 3,
    "status": "Cancelado",
    "number_registered": 20,
    "link": null,
    "rrss": 10,
    "sms": 20,
    "mail": 10
  },



  
];

export default data;